# Generated by Django 5.2 on 2025-04-28 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='原始圖片')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='results/%Y/%m/%d/', verbose_name='標註結果圖')),
                ('results_data', models.JSONField(blank=True, null=True, verbose_name='辨識結果數據')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
            ],
            options={
                'verbose_name': '辨識紀錄',
                'verbose_name_plural': '辨識紀錄',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
