# Generated by Django 5.2.1 on 2025-05-17 17:31

import detector.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDetectionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='批次任務 ID')),
                ('celery_task_id', models.CharField(blank=True, help_text='觸發此批次的主 Celery 任務 ID (process_s3_folder_task)', max_length=255, null=True, verbose_name='Celery 批次任務 ID')),
                ('s3_bucket_name', models.CharField(max_length=255, verbose_name='S3 儲存桶名稱')),
                ('s3_folder_prefix', models.CharField(max_length=1024, verbose_name='S3 資料夾路徑')),
                ('status', models.CharField(choices=[('PENDING', '待處理'), ('PROCESSING', '處理中'), ('COMPLETED', '已完成'), ('PARTIAL_COMPLETION', '部分完成'), ('FAILED', '失敗')], default='PENDING', max_length=20, verbose_name='批次狀態')),
                ('total_images_found', models.IntegerField(default=0, verbose_name='找到的圖片總數')),
                ('images_processed_successfully', models.IntegerField(default=0, verbose_name='成功處理圖片數')),
                ('images_failed_to_process', models.IntegerField(default=0, verbose_name='處理失敗圖片數')),
                ('summary_results', models.JSONField(blank=True, null=True, verbose_name='批次摘要結果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='批次錯誤訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '批次辨識任務',
                'verbose_name_plural': '批次辨識任務',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='severity_score',
            field=models.FloatField(blank=True, help_text='數值越高代表越嚴重 (例如 0.0 至 1.0)', null=True, verbose_name='嚴重程度評分'),
        ),
        migrations.AlterField(
            model_name='detectionrecord',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to=detector.models.get_annotated_image_upload_path, verbose_name='標註結果圖'),
        ),
        migrations.AlterField(
            model_name='detectionrecord',
            name='original_image',
            field=models.ImageField(upload_to=detector.models.get_original_image_upload_path, verbose_name='原始圖片'),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='batch_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_records', to='detector.batchdetectionjob', verbose_name='所屬批次任務'),
        ),
    ]
