# Generated by Django 5.2.1 on 2025-05-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_batchdetectionjob_detectionrecord_severity_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='batch_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_records', to='detector.batchdetectionjob', verbose_name='所屬批次任務'),
        ),
    ]
